import LocalizedStrings from 'react-native-localization';

export let strings = new LocalizedStrings({
    en: {
        translate: "Translate",
        translateArea: "Translate Area",
        enterText: "Enter Text",
        translation: "Translation",
        historyFav: "History/Fav",
        history: "History",
        favorite: "Favorite",
        settings: "Settings",
        edit: "Edit",
        language: "Language",
        languageHint: "You can change it in the settings of your device",
        wordHistory: "Word history",
        signOut: "Sign Out",
        profile: "Profile",
        username: "Username",
        email: "Email",
        deleteAccount: "Delete account",
        cancel: "Cancel",
        update: "Update",
        password: "Password",
        passwordDescription: "Create a new password for yourself.",
        createPassword: "Create password",
        passwordAgain: "Password again",
        atLeast8: "Must be at least 8 characters.",
        loading: "Loading",
        customFailMessage1: "Something went wrong!",
        customFailMessage2: "Profile information couldn't fetched.",
        customFailMessage3: "Username or email used. Please try again.",
        modal1: "Are you sure you want to log out?",
        modal2: "Enter your password to edit the profile.",
        customSuccessMessage1: "Password has been changed.",
        customSuccessMessage2: "User infromation has been changed.",
        noWord: "You have no word: ",
        result: "result found",
        filter: "Filter",
        standart: "Standart",
        descending: "Newest",
        ascending: "Oldest",
        search: "Search",
        createUsername: "Create Username",
        enterYourEmail: "Enter your email",
        enterPasswordAgain: "Enter your password again",
        complete: "Complete",
        continue: "Continue",
        accountCreating: "Account is being creating...",
        alreadyHaveAccount: "I already have an account",
        login: "Login",
        back: "Back",
        register: "Register",
        rememberMe: "Remember me!",
        dontHaveAccount: "Don't have an account?",
        forgotYourPassword: "Forgot your password?",
        loginLoading: "Logging in...",
        orSignInWith: "Or login with:"
    },
    tr: {
        translate: "Çevir",
        translateArea: "Çeviri Yeri",
        enterText: "Metin girin",
        translation: "Tercüme",
        historyFav: "Geçmiş/Favoriler",
        history: "Gemiş",
        favorite: "Favoriler",
        settings: "Ayarlar",
        edit: "Düzenle",
        language: "Dil",
        languageHint: "Cihazınızın ayarlar bölümünden değiştirebilirsiniz",
        wordHistory: "Kelime geçmişi",
        signOut: "Çıkış Yap",
        profile: "Profil",
        username: "Kullanıcı adı",
        email: "Email",
        deleteAccount: "Hesabı sil",
        cancel: "Vazgeç",
        update: "Güncelle",
        password: "Şifre",
        passwordDescription: "Kenidiniz için bir şifre belirleyin.",
        createPassword: "Şifrenizi oluşturun",
        passwordAgain: "Şifrenizi tekrar yazın",
        atLeast8: "Şifreniz en az 8 karakter olmalıdır.",
        loading: "Yükleniyor",
        customFailMessage1: "Beklenmeyen bir hata oluştu!",
        customFailMessage2: "Profil bilgileri getirilemedi",
        customFailMessage3: "Kullanıcı adı veya şifre kullanılmış. Lütfen tekrar deneyin.",
        modal1: "Çıkmak istediğinize emin misiniz?",
        modal2: "Profili editlemek için şifrenizi girin",
        customSuccessMessage1: "Parolanız başarıyla değiştirildi.",
        customSuccessMessage2: "Kullanıcı bilgileri değiştirildi.",
        noWord: "Hiç kelimeniz yok: ",
        result: "sonuç bulundu.",
        filter: "Filtre",
        standart: "Standart",
        descending: "Yeniler",
        ascending: "Eskiler",
        search: "Ara",
        createUsername: "Kullanıcı adı oluştur",
        enterYourEmail: "Emailini gir",
        enterPasswordAgain: "Şifrenizi tekrar girin",
        complete: "Tamamla",
        continue: "Devam et",
        accountCreating: "Hesap oluşturuluyor...",
        alreadyHaveAccount: "Zaten hesabım var",
        login: "Giriş",
        back: "Geri",
        register: "Kayıt ol",
        rememberMe: "Beni hatırla",
        dontHaveAccount: "Hesabınız yok mu?",
        forgotYourPassword: "Şifrenizi mi unuttunuz?",
        loginLoading: "Giriş yapılıyor...",
        orSignInWith: "Veya:"
    }
});
