import LocalizedStrings from 'react-native-localization';

export let strings = new LocalizedStrings({
    en: {
        translate: "Translate",
        translateArea: "Translate Area",
        enterText: "Enter Text",
        translation: "Translation",
        historyFav: "History/Fav",
        history: "History",
        favorite: "Favorite",
        settings: "Settings",
        edit: "Edit",
        language: "Language",
        languageHint: "The application language changes automatically according to your device language.",
        wordHistory: "Word history",
        signOut: "Sign Out",
        profile: "Profile",
        username: "Username",
        email: "Email",
        deleteAccount: "Delete account",
        cancel: "Cancel",
        update: "Update",
        password: "Password",
        passwordDescription: "Create a new password for yourself.",
        createPassword: "Create password",
        passwordAgain: "Password again",
        atLeast8: "Must be at least 8 characters.",
        loading: "Loading",
        customFailMessage1: "Something went wrong!",
        customFailMessage2: "Profile information couldn't fetched.",
        customFailMessage3: "Username or email used. Please try again.",
        modal1: "Are you sure you want to log out?",
        modal2: "Enter your password to edit the profile.",
        modal3: "Are you sure you want to DELETE your account?",
        customSuccessMessage1: "Password has been changed.",
        customSuccessMessage2: "User informations has been changed.",
        customInfoMessage1: "Password change is disabled for social media login.",
        customInfoMessage2: "Your account has been deleted.",
        noWord: "You have no word: ",
        result: "result found",
        filter: "Filter",
        standart: "Standart",
        descending: "Newest",
        ascending: "Oldest",
        search: "Search",
        createUsername: "Create Username",
        enterYourEmail: "Enter your email",
        enterPasswordAgain: "Enter your password again",
        complete: "Complete",
        continue: "Continue",
        accountCreating: "Account is being creating...",
        alreadyHaveAccount: "I already have an account",
        login: "Login",
        back: "Back",
        register: "Register",
        rememberMe: "Remember me!",
        dontHaveAccount: "Don't have an account?",
        forgotYourPassword: "Forgot your password?",
        loginLoading: "Logging in",
        orSignInWith: "Or login with:",
        creatingUser: "Creating User",
        socialEmailChangeInfo: "Email editing disabled on social media login",
        terms: "Terms and conditions",
        termsShort: "Terms",
        policy: "Privacy policy",
        policyShort: "Privacy",
        acceptPrivTerms: "When creating an account, you agree to the following:"
    },
    tr: {
        translate: "Çevir",
        translateArea: "Çeviri Yeri",
        enterText: "Metin girin",
        translation: "Tercüme",
        historyFav: "Geçmiş/Favoriler",
        history: "Gemiş",
        favorite: "Favoriler",
        settings: "Ayarlar",
        edit: "Düzenle",
        language: "Dil",
        languageHint: "Uygulama dili, cihaz dilinize göre otomatik değişmektedir.",
        wordHistory: "Kelime geçmişi",
        signOut: "Çıkış Yap",
        profile: "Profil",
        username: "Kullanıcı adı",
        email: "Email",
        deleteAccount: "Hesabı sil",
        cancel: "Vazgeç",
        update: "Güncelle",
        password: "Şifre",
        passwordDescription: "Kenidiniz için bir şifre belirleyin.",
        createPassword: "Şifrenizi oluşturun",
        passwordAgain: "Şifrenizi tekrar yazın",
        atLeast8: "Şifreniz en az 8 karakter olmalıdır.",
        loading: "Yükleniyor",
        customFailMessage1: "Beklenmeyen bir hata oluştu!",
        customFailMessage2: "Profil bilgileri getirilemedi",
        customFailMessage3: "Kullanıcı adı veya şifre kullanılmış. Lütfen tekrar deneyin.",
        modal1: "Çıkmak istediğinize emin misiniz?",
        modal2: "Profili editlemek için şifrenizi girin",
        modal3: "Hesabınızı silmek istediğinize emin misiniz?",
        customSuccessMessage1: "Parolanız başarıyla değiştirildi.",
        customSuccessMessage2: "Kullanıcı bilgileri değiştirildi.",
        customInfoMessage1: "Sosyal medya girişlerinde şifre değiştirme devre dışı.",
        customInfoMessage2: "Hesabınız silinmiştir.",
        noWord: "Hiç kelimeniz yok: ",
        result: "sonuç bulundu.",
        filter: "Filtre",
        standart: "Standart",
        descending: "Yeniler",
        ascending: "Eskiler",
        search: "Ara",
        createUsername: "Kullanıcı adı oluştur",
        enterYourEmail: "Emailini gir",
        enterPasswordAgain: "Şifrenizi tekrar girin",
        complete: "Tamamla",
        continue: "Devam et",
        accountCreating: "Hesap oluşturuluyor...",
        alreadyHaveAccount: "Zaten hesabım var",
        login: "Giriş",
        back: "Geri",
        register: "Kayıt ol",
        rememberMe: "Beni hatırla",
        dontHaveAccount: "Hesabınız yok mu?",
        forgotYourPassword: "Şifrenizi mi unuttunuz?",
        loginLoading: "Giriş yapılıyor",
        orSignInWith: "Veya:",
        creatingUser: "Kullanıcı oluşturuluyor",
        socialEmailChangeInfo: "Sosyal medya girişlerinde email düzenleme devre dışı",
        terms: "Kullanım koşulları",
        termsShort: "Kul. koşulları",
        policy: "Gizlilik politikası",
        policyShort: "Gizlilik",
        acceptPrivTerms: "Hesap oluştururken aşağıdakileri kabul etmiş sayılırsınız:"
    },
    es: {
        translate: "Traducir",
        translateArea: "Traducir área",
        enterText: "Ingrese texto",
        translation: "Traducción",
        historyFav: "Historia/Favoritos",
        history: "Historia",
        favorite: "Favorito",
        settings: "Ajustes",
        edit: "Editar",
        language: "Idioma",
        languageHint: "El idioma de la aplicación cambia automáticamente según el idioma de su dispositivo.",
        wordHistory: "Historia de la palabra",
        signOut: "Desconectar",
        profile: "Perfil",
        username: "Nombre de usuario",
        email: "Correo electrónico",
        deleteAccount: "Borrar cuenta",
        cancel: "Cancelar",
        update: "Actualizar",
        password: "Clave",
        passwordDescription: "Cree una nueva contraseña para usted.",
        createPassword: "Crear contraseña",
        passwordAgain: "Contraseña de nuevo",
        atLeast8: "Debe tener al menos 8 caracteres.",
        loading: "Cargando",
        customFailMessage1: "¡Algo salió mal!",
        customFailMessage2: "No se pudo obtener la información del perfil.",
        customFailMessage3: "Nombre de usuario o correo electrónico utilizado. Inténtalo de nuevo.",
        modal1: "¿Estás seguro de que quieres cerrar sesión?",
        modal2: "Introduzca su contraseña para editar el perfil.",
        modal3: "¿Estás seguro de que deseas ELIMINAR tu cuenta?",
        customSuccessMessage1: "La contraseña ha sido cambiada.",
        customSuccessMessage2: "La información del usuario ha sido cambiada.",
        customInfoMessage1: "El cambio de contraseña está deshabilitado para el inicio de sesión en las redes sociales.",
        customInfoMessage2: "Tu cuenta ha sido eliminada.",
        noWord: "No tienes palabra: ",
        result: "resultado encontrado",
        filter: "Filtrar",
        standart: "Estándar",
        descending: "El mas nuevo",
        ascending: "Más antiguo",
        search: "Búsqueda",
        createUsername: "Crear nombre de usuario",
        enterYourEmail: "Introduce tu correo electrónico",
        enterPasswordAgain: "Introduce tu contraseña de nuevo",
        complete: "Completo",
        continue: "Continuar",
        accountCreating: "La cuenta se está creando...",
        alreadyHaveAccount: "ya tengo una cuenta",
        login: "Acceso",
        back: "atrás",
        register: "Registro",
        rememberMe: "¡Acuérdate de mí!",
        dontHaveAccount: "¿No tienes una cuenta?",
        forgotYourPassword: "¿Olvidaste tu contraseña?",
        loginLoading: "Iniciando sesión",
        orSignInWith: "O inicia sesión con:",
        creatingUser: "Creando usuario",
        socialEmailChangeInfo: "Edición de correo electrónico deshabilitada en el inicio de sesión de redes sociales",
        terms: "Términos y condiciones",
        termsShort: "Términos",
        policy: "Política de privacidad",
        policyShort: "Privacidad",
        acceptPrivTerms: "Al crear una cuenta, usted acepta lo siguiente:"
    },
});
